version: '3'
services:
  reports-db:
    container_name: reports-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: result
    ports:
      - "5432:5432"
  active-users-db:
    container_name: active-users-postgres
    volumes:
      - ./databases/users/active/:/docker-entrypoint-initdb.d/
    image: postgres:latest
    environment:
      POSTGRES_USER: active-users
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: active-users
    ports:
      - "5442:5432"
